apiVersion: v1
kind: Service
metadata:
  name: sts
  namespace: sts
  labels:
    app: sts
spec:
  type: ClusterIP
  selector:
    app: sts
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80